--SCRIPT_MANIFIESTAPOLI CON SQL

--DROPS TABLES
DROP TABLE Conversacion_Informe
GO

ALTER TABLE Conversacion_Informe 
    DROP CONSTRAINT Conversacion_Informe_CONVERSACIONES_FK 
GO

ALTER TABLE HISTORIALES 
    DROP CONSTRAINT HISTORIALES_CONVERSACIONES_FK 
GO

ALTER TABLE MENSAJES 
    DROP CONSTRAINT MENSAJES_CONVERSACIONES_FK 
GO

DROP TABLE CONVERSACIONES
GO

DROP TABLE HISTORIALES
GO

ALTER TABLE Conversacion_Informe 
    DROP CONSTRAINT Conversacion_Informe_INFORMES_FK 
GO

DROP TABLE INFORMES
GO

DROP TABLE INTENTOS
GO

ALTER TABLE Mensajes_respuestas 
    DROP CONSTRAINT Mensajes_respuestas_MENSAJES_FK 
GO

ALTER TABLE Preguntas_Mensajes 
    DROP CONSTRAINT PreRes_Mensajes_MENSAJES_FK 
GO

DROP TABLE MENSAJES
GO

DROP TABLE Mensajes_respuestas
GO

ALTER TABLE Preguntas_Mensajes 
    DROP CONSTRAINT PreRes_Mensajes_PREGUNTAS_FK 
GO

DROP TABLE PREGUNTAS
GO

DROP TABLE Preguntas_Mensajes
GO

ALTER TABLE Mensajes_respuestas 
    DROP CONSTRAINT Mensajes_respuestas_RESPUESTAS_FK 
GO

DROP TABLE RESPUESTAS
GO

ALTER TABLE CONVERSACIONES 
    DROP CONSTRAINT CONVERSACIONES_SESIONES_FK 
GO

ALTER TABLE USUARIOS 
    DROP CONSTRAINT USUARIOS_SESIONES_FK 
GO

DROP TABLE SESIONES
GO

ALTER TABLE INTENTOS 
    DROP CONSTRAINT INTENTOS_USUARIOS_FK 
GO

ALTER TABLE SESIONES 
    DROP CONSTRAINT SESIONES_USUARIOS_FK 
GO

DROP TABLE USUARIOS
GO


--CREATES TABLES
CREATE TABLE Conversacion_Informe 
    (
     INFORMES_ID_Informe VARCHAR (30) NOT NULL , 
     CONVERSACIONES_ID_Conversacion INTEGER NOT NULL 
    )
GO

ALTER TABLE Conversacion_Informe ADD CONSTRAINT Conversacion_Informe_PK PRIMARY KEY CLUSTERED (INFORMES_ID_Informe, CONVERSACIONES_ID_Conversacion)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE CONVERSACIONES 
    (
     ID_Conversacion INTEGER NOT NULL , 
     SESIONES_ID_Sesion INTEGER NOT NULL 
    )
GO

ALTER TABLE CONVERSACIONES ADD CONSTRAINT CONVERSACIONES_PK PRIMARY KEY CLUSTERED (ID_Conversacion)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE HISTORIALES 
    (
     ID_Historial INTEGER NOT NULL , 
     CONVERSACIONES_ID_Conversacion INTEGER NOT NULL 
    )
GO 

    


CREATE UNIQUE NONCLUSTERED INDEX 
    HISTORIALES__IDX ON HISTORIALES 
    ( 
     CONVERSACIONES_ID_Conversacion 
    ) 
GO

ALTER TABLE HISTORIALES ADD CONSTRAINT HISTORIALES_PK PRIMARY KEY CLUSTERED (ID_Historial)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE INFORMES 
    (
     ID_Informe VARCHAR (30) NOT NULL 
    )
GO

ALTER TABLE INFORMES ADD CONSTRAINT INFORMES_PK PRIMARY KEY CLUSTERED (ID_Informe)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE INTENTOS 
    (
     ID_Intento INTEGER NOT NULL , 
     Contenido VARCHAR (100) NOT NULL , 
     Marca_Tiempo DATETIME NOT NULL , 
     Exito BIT NOT NULL , 
     USUARIOS_ID_Usuario INTEGER NOT NULL 
    )
GO

ALTER TABLE INTENTOS ADD CONSTRAINT INTENTOS_PK PRIMARY KEY CLUSTERED (ID_Intento)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE MENSAJES 
    (
     ID_Mensaje INTEGER NOT NULL , 
     Marca_Tiempo DATETIME NOT NULL , 
     Contenido VARCHAR (100) NOT NULL , 
     ID_Emisor INTEGER NOT NULL , 
     CONVERSACIONES_ID_Conversacion INTEGER NOT NULL 
    )
GO

ALTER TABLE MENSAJES ADD CONSTRAINT MENSAJES_PK PRIMARY KEY CLUSTERED (ID_Mensaje)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Mensajes_respuestas 
    (
     MENSAJES_ID_Mensaje INTEGER NOT NULL , 
     RESPUESTAS_ID_Respuestas INTEGER NOT NULL 
    )
GO

ALTER TABLE Mensajes_respuestas ADD CONSTRAINT Mensajes_respuestas_PK PRIMARY KEY CLUSTERED (MENSAJES_ID_Mensaje, RESPUESTAS_ID_Respuestas)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE PREGUNTAS 
    (
     ID_Preguntas INTEGER NOT NULL , 
     Contenido VARCHAR (100) NOT NULL 
    )
GO

ALTER TABLE PREGUNTAS ADD CONSTRAINT PREGUNTAS_PK PRIMARY KEY CLUSTERED (ID_Preguntas)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Preguntas_Mensajes 
    (
     PREGUNTAS_ID_Preguntas INTEGER NOT NULL , 
     MENSAJES_ID_Mensaje INTEGER NOT NULL 
    )
GO

ALTER TABLE Preguntas_Mensajes ADD CONSTRAINT PreRes_Mensajes_PK PRIMARY KEY CLUSTERED (PREGUNTAS_ID_Preguntas, MENSAJES_ID_Mensaje)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE RESPUESTAS 
    (
     ID_Respuestas INTEGER NOT NULL , 
     Contenido VARCHAR (100) NOT NULL 
    )
GO

ALTER TABLE RESPUESTAS ADD CONSTRAINT RESPUESTAS_PK PRIMARY KEY CLUSTERED (ID_Respuestas)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE SESIONES 
    (
     ID_Sesion INTEGER NOT NULL , 
     ID_Chatbot INTEGER NOT NULL , 
     USUARIOS_ID_Usuario INTEGER NOT NULL 
    )
GO 

CREATE UNIQUE NONCLUSTERED INDEX 
    SESIONES__IDX ON SESIONES 
    ( 
     USUARIOS_ID_Usuario 
    ) 
GO

ALTER TABLE SESIONES ADD CONSTRAINT SESIONES_PK PRIMARY KEY CLUSTERED (ID_Sesion)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE USUARIOS 
    (
     ID_Usuario INTEGER NOT NULL , 
     Email VARCHAR (40) NOT NULL , 
     Nombre VARCHAR (30) NOT NULL , 
     Apellido VARCHAR (30) NOT NULL , 
     Contraseña VARCHAR (30) NOT NULL , 
     Programa_Academico VARCHAR (30) , 
     Ocupación VARCHAR (20) , 
     SESIONES_ID_Sesion INTEGER NOT NULL 
    )
GO 

    


CREATE UNIQUE NONCLUSTERED INDEX 
    USUARIOS__IDX ON USUARIOS 
    ( 
     SESIONES_ID_Sesion 
    ) 
GO

ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS_PK PRIMARY KEY CLUSTERED (ID_Usuario)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Conversacion_Informe 
    ADD CONSTRAINT Conversacion_Informe_CONVERSACIONES_FK FOREIGN KEY 
    ( 
     CONVERSACIONES_ID_Conversacion
    ) 
    REFERENCES CONVERSACIONES 
    ( 
     ID_Conversacion 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Conversacion_Informe 
    ADD CONSTRAINT Conversacion_Informe_INFORMES_FK FOREIGN KEY 
    ( 
     INFORMES_ID_Informe
    ) 
    REFERENCES INFORMES 
    ( 
     ID_Informe 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CONVERSACIONES 
    ADD CONSTRAINT CONVERSACIONES_SESIONES_FK FOREIGN KEY 
    ( 
     SESIONES_ID_Sesion
    ) 
    REFERENCES SESIONES 
    ( 
     ID_Sesion 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE HISTORIALES 
    ADD CONSTRAINT HISTORIALES_CONVERSACIONES_FK FOREIGN KEY 
    ( 
     CONVERSACIONES_ID_Conversacion
    ) 
    REFERENCES CONVERSACIONES 
    ( 
     ID_Conversacion 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE INTENTOS 
    ADD CONSTRAINT INTENTOS_USUARIOS_FK FOREIGN KEY 
    ( 
     USUARIOS_ID_Usuario
    ) 
    REFERENCES USUARIOS 
    ( 
     ID_Usuario 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MENSAJES 
    ADD CONSTRAINT MENSAJES_CONVERSACIONES_FK FOREIGN KEY 
    ( 
     CONVERSACIONES_ID_Conversacion
    ) 
    REFERENCES CONVERSACIONES 
    ( 
     ID_Conversacion 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Mensajes_respuestas 
    ADD CONSTRAINT Mensajes_respuestas_MENSAJES_FK FOREIGN KEY 
    ( 
     MENSAJES_ID_Mensaje
    ) 
    REFERENCES MENSAJES 
    ( 
     ID_Mensaje 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Mensajes_respuestas 
    ADD CONSTRAINT Mensajes_respuestas_RESPUESTAS_FK FOREIGN KEY 
    ( 
     RESPUESTAS_ID_Respuestas
    ) 
    REFERENCES RESPUESTAS 
    ( 
     ID_Respuestas 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Preguntas_Mensajes 
    ADD CONSTRAINT PreRes_Mensajes_MENSAJES_FK FOREIGN KEY 
    ( 
     MENSAJES_ID_Mensaje
    ) 
    REFERENCES MENSAJES 
    ( 
     ID_Mensaje 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Preguntas_Mensajes 
    ADD CONSTRAINT PreRes_Mensajes_PREGUNTAS_FK FOREIGN KEY 
    ( 
     PREGUNTAS_ID_Preguntas
    ) 
    REFERENCES PREGUNTAS 
    ( 
     ID_Preguntas 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SESIONES 
    ADD CONSTRAINT SESIONES_USUARIOS_FK FOREIGN KEY 
    ( 
     USUARIOS_ID_Usuario
    ) 
    REFERENCES USUARIOS 
    ( 
     ID_Usuario 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE USUARIOS 
    ADD CONSTRAINT USUARIOS_SESIONES_FK FOREIGN KEY 
    ( 
     SESIONES_ID_Sesion
    ) 
    REFERENCES SESIONES 
    ( 
     ID_Sesion 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

